version: '3'
services:

 billingcontract:
   environment:
    - BILLING_CONTRACT_DB=mysql://root:root@db:3306/billing_contract
    - kafka.bootstrap-servers=kafka:9092
 #docker.for.mac.localhost placeholder gets replaced with the host IP host when running on mac
   image: jordanwb85/billingcontract #aws_container_repo_billingcontract
   ports:
    - "8080:8080"
   depends_on:
    - db
    - kafka
    - zipkin

 db:
  image: mysql:5.6.37
  restart: always
  environment:
   - MYSQL_ROOT_PASSWORD=root

 kafka:
  image: spotify/kafka
  hostname: kafka
  environment:
   - ADVERTISED_HOST=kafka
   - ADVERTISED_PORT=9092
  ports:
   - "2181:2181"
   - "9092:9092"

 zipkin:
  image: openzipkin/zipkin
  ports:
   - "9411:9411"
